version: '3.8'

# helpful commands:
#
# list running containers:
# docker ps
#
# show details for postgres container named 'pg-tsrx':
# docker ps -f "name=pg-tsrx"

# port mapping follows the convention:
# host_port:container_port

services:
  postgres:
    container_name: pg-tsrx
    image: 'postgres:15.4'
    environment:
      TZ: UTC
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped
    mem_limit: 512m
    cpus: '0.50'
    # `volumes` entrypoint will only run if data directory is empty (https://hub.docker.com/_/postgres/)
    # ./db/initdb.d:/docker-entrypoint-initdb.d

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #       - 8080:8080

  # docker compose start pgadmin
  #
  pgadmin:
    container_name: pgadmin-tsrx
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - '5050:80'
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app_network

# persist data across container restarts
volumes:
  pg-data:
  pgadmin-data:

networks:
  app_network:
    driver: bridge
